# Лабораторная работа 1.

## Задание: Создать шахматную доску с помощью метода tile

In [12]:
import numpy as np

chessboard = np.tile(np.array([[1, 0], [0, 1]]), (4, 4))

print(chessboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
